export { default as BgStars } from './BgStars/index.vue'
export { default as Sun } from './Sun/index.vue'
export { default as System } from './System/index.vue'
export { default as Planet } from './Planet/index.vue'
export { default as Map } from './Map/index.vue'
